spring:
  application:
    name: consumer
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        "[default_schema]": history
  kafka:
    bootstrap-servers:
    - kafka:9092
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
    listener:
      missing-topics-fatal: true
      ack-mode: manual-immediate
      poll-timeout: 3000
    
application:
  topic-owner: db.public.owner
  owner-group-id: history-owner-consumer
  topic-cars: db.public.cars
  cars-group-id: history-cars-consumer
